package com.bitcoinwukong.robosats_android.model

enum class Currency(val id: Int, val code: String) {
    ALL(0, "ALL"),
    USD(1, "USD"),
    EUR(2, "EUR"),
    JPY(3, "JPY"),
    GBP(4, "GBP"),
    AUD(5, "AUD"),
    CAD(6, "CAD"),
    CHF(7, "CHF"),
    CNY(8, "CNY"),
    HKD(9, "HKD"),
    NZD(10, "NZD"),
    SEK(11, "SEK"),
    KRW(12, "KRW"),
    SGD(13, "SGD"),
    NOK(14, "NOK"),
    MXN(15, "MXN"),
    BYN(16, "BYN"),
    RUB(17, "RUB"),
    ZAR(18, "ZAR"),
    TRY(19, "TRY"),
    BRL(20, "BRL"),
    CLP(21, "CLP"),
    CZK(22, "CZK"),
    DKK(23, "DKK"),
    HRK(24, "HRK"),
    HUF(25, "HUF"),
    INR(26, "INR"),
    ISK(27, "ISK"),
    PLN(28, "PLN"),
    RON(29, "RON"),
    ARS(30, "ARS"),
    VES(31, "VES"),
    COP(32, "COP"),
    PEN(33, "PEN"),
    UYU(34, "UYU"),
    PYG(35, "PYG"),
    BOB(36, "BOB"),
    IDR(37, "IDR"),
    ANG(38, "ANG"),
    CRC(39, "CRC"),
    CUP(40, "CUP"),
    DOP(41, "DOP"),
    GHS(42, "GHS"),
    GTQ(43, "GTQ"),
    ILS(44, "ILS"),
    JMD(45, "JMD"),
    KES(46, "KES"),
    KZT(47, "KZT"),
    MYR(48, "MYR"),
    NAD(49, "NAD"),
    NGN(50, "NGN"),
    AZN(51, "AZN"),
    PAB(52, "PAB"),
    PHP(53, "PHP"),
    PKR(54, "PKR"),
    QAR(55, "QAR"),
    SAR(56, "SAR"),
    THB(57, "THB"),
    TTD(58, "TTD"),
    VND(59, "VND"),
    XOF(60, "XOF"),
    TWD(61, "TWD"),
    TZS(62, "TZS"),
    XAF(63, "XAF"),
    UAH(64, "UAH"),
    EGP(65, "EGP"),
    LKR(66, "LKR"),
    MAD(67, "MAD"),
    AED(68, "AED"),
    TND(69, "TND"),
    ETB(70, "ETB"),
    GEL(71, "GEL"),
    UGX(72, "UGX"),
    RSD(73, "RSD"),
    IRT(74, "IRT"),
    BDT(75, "BDT"),
    XAU(300, "XAU"),
    BTC(1000, "BTC");

    companion object {
        fun fromId(id: Int): Currency {
            return values().firstOrNull { it.id == id }
                ?: throw IllegalArgumentException("Invalid currency id: $id")
        }
    }
}
