package com.bitcoinwukong.robosats_android.model

enum class PaymentMethod(val methodName: String) {
    REVOLUT("Revolut"),
    CASH_APP("CashApp"),
    ZELLE("Zelle"),
    STRIKE("Strike"),
    WECHAT_PAY("WeChat Pay"),
    REBELLION("Rebellion"),
    INSTANT_SEPA("Instant SEPA"),
    INTERAC_E_TRANSFER("Interac e-Transfer"),
    WISE("Wise"),
    VENMO("Venmo"),
    FASTER_PAYMENTS("Faster Payments"),
    PAYPAL_FRIENDS_FAMILY("Paypal Friends & Family"),
    LINE_PAY("LINE Pay"),
    RAKUTEN_PAY("Rakuten Pay"),
    PROMPTPAY("PromptPay"),
    BIZUM("Bizum"),
    N26("N26"),
    TINKOFF_BANK("Tinkoff Bank"),
    TWINT("TWINT"),
    ADVCASH("Advcash"),
    BLIK("BLIK"),
    MBWAY("MBWay"),
    W1TTY("W1TTY"),
    VERSE("Verse"),
    PAYSERA("Paysera"),
    AMAZON_GIFTCARD("Amazon GiftCard"),
    OZON_GIFTCARD("Ozon GiftCard"),
    ALIPAY("AliPay"),
    GPAY("GPay"),
    BANCOLOMBIA("Bancolombia"),
    PAGO_MOVIL_BDV("Pago Movil BDV"),
    SPEI("SPEI"),
    PIX("PIX"),
    POUCH_PH("Pouch.ph"),
    PAYID("PayID"),
    PAYSAFE("Paysafe"),
    SBER_BANK("Sber Bank"),
    PHONEPE("PhonePe"),
    OVO("OVO"),
    HALCASH("HalCash"),
    VIVID("Vivid"),
    GOOGLE_PLAY_GIFT_CODE("Google Play Gift Code"),
    APPLE_PAY("Apple Pay"),
    STEAM("Steam"),
    NEQUI("Nequi"),
    SHAKEPAY("ShakePay"),
    SINPE("Sinpe"),
    DAVIPLATA("DaviPlata"),
    CODI("CoDi"),
    TAIWANPAY("TaiwanPay"),
    MAICOIN("MaiCoin"),
    GOPAY("GoPay"),
    MERCADOPAGO("MercadoPago"),
    MONERO("Monero"),
    USDT("USDT"),
    L_USDT("L-USDt"),
    AIRTEL_MONEY("Airtel Money"),
    MTN_MONEY("MTN Money"),
    M_PESA("M-Pesa"),
    UPI("UPI"),
    MOMO("MoMo"),
    TIGO_PESA("Tigo Pesa"),
    CASH_F2F("Cash F2F"),
    AMAZON_USA_GIFTCARD("Amazon USA GiftCard"),
    AMAZON_DE_GIFTCARD("Amazon DE GiftCard"),
    AMAZON_AU_GIFTCARD("Amazon AU GiftCard"),
    AMAZON_SA_GIFTCARD("Amazon SA GiftCard"),
    AMAZON_ES_GIFTCARD("Amazon ES GiftCard"),
    AMAZON_CA_GIFTCARD("Amazon CA GiftCard"),
    AMAZON_CN_GIFTCARD("Amazon CN GiftCard"),
    AMAZON_AE_GIFTCARD("Amazon AE GiftCard"),
    AMAZON_FR_GIFTCARD("Amazon FR GiftCard"),
    AMAZON_NL_GIFTCARD("Amazon NL GiftCard"),
    AMAZON_IN_GIFTCARD("Amazon IN GiftCard"),
    AMAZON_IT_GIFTCARD("Amazon IT GiftCard"),
    AMAZON_JP_GIFTCARD("Amazon JP GiftCard"),
    AMAZON_MX_GIFTCARD("Amazon MX GiftCard"),
    AMAZON_PL_GIFTCARD("Amazon PL GiftCard"),
    AMAZON_UK_GIFTCARD("Amazon UK GiftCard"),
    AMAZON_SE_GIFTCARD("Amazon SE GiftCard"),
    AMAZON_SG_GIFTCARD("Amazon SG GiftCard"),
    AMAZON_TR_GIFTCARD("Amazon TR GiftCard"),
    TINKOFF_QR("Tinkoff QR"),
    SBP("SBP"),
    QIWI("Qiwi"),
    CUSTOM("Custom");

    companion object {
        fun fromString(methodName: String): PaymentMethod {
            return values().firstOrNull { it.methodName.equals(methodName, ignoreCase = true) } ?: CUSTOM
        }

        fun toString(method: PaymentMethod): String {
            return method.methodName
        }
    }
}
